In [88]:
import pandas as pd
import numpy as np
import os

In [89]:
path2target = '/Users/y1u0d2/desktop/Lab/result/n2p2/Si/07/rc_5-np_9'

In [90]:
with open(os.path.join(path2target, 'input.data'), mode='r') as f:
    l_strip = [s.strip() for s in f.readlines()]
    
all_data = list(filter(lambda x: 'comment' in x, l_strip))

In [91]:
with open(os.path.join(path2target, 'test.data'), mode='r') as f:
    l_strip = [s.strip() for s in f.readlines()]
    
test_data = list(filter(lambda x: 'comment' in x, l_strip))

In [92]:
with open(os.path.join(path2target, 'train.data'), mode='r') as f:
    l_strip = [s.strip() for s in f.readlines()]
    
train_data = list(filter(lambda x: 'comment' in x, l_strip))

In [93]:
all_df = pd.DataFrame(data=all_data, columns=['comment'])

In [94]:
all_df = all_df.reset_index()
all_df = all_df.rename(columns={'index': 'structure_idx'})

In [95]:
test_df = pd.DataFrame(data=test_data, columns=['comment'])
train_df = pd.DataFrame(data=train_data, columns=['comment'])

In [96]:
test_structure_ids = pd.merge(all_df, test_df, on='comment', how='right')
train_structure_ids = pd.merge(all_df, train_df, on='comment', how='right')

In [97]:
def get_materials_id_from_comment(val):
    splitted_path = val.split('/')
    id = list(filter(lambda x: 'mp-' in x, splitted_path))[0]
    return id

test_structure_ids['materials_id'] = test_structure_ids['comment'].map(get_materials_id_from_comment)
train_structure_ids['materials_id'] = train_structure_ids['comment'].map(get_materials_id_from_comment)

In [98]:
test_structure_ids

,structure_idx,comment,materials_id
0,165,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
1,369,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
2,446,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
3,564,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-109
4,578,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-109
...,...,...,...
285,2403,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
286,2489,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
287,2598,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
288,2691,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
289,2717,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168

In [100]:
train_structure_ids

,structure_idx,comment,materials_id
0,2,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
1,3,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
2,33,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
3,44,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
4,72,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
...,...,...,...
2692,2678,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
2693,2718,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
2694,2767,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
2695,2783,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
2696,2810,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168

In [3]:
from analyze.get_structure_index import get_structure_idx

path2target = '/Users/y1u0d2/desktop/Lab/result/n2p2/Si/07/rc_5-np_9'
test_structure_idx, train_structure_idx = get_structure_idx(path2target)

In [4]:
test_structure_idx

,structure_idx,comment,materials_id
0,165,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
1,369,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
2,446,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-1079649
3,564,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-109
4,578,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-109
...,...,...,...
285,2403,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
286,2489,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
287,2598,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
288,2691,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168
289,2717,comment /Users/y1u0d2/desktop/Lab/result/qe/Si...,mp-168